#!/usr/bin/env python

from distutils.core import setup
setup(name='PyWebDAV',
      description='WebDAV library and server for python',
      author='Christian Scholz',
      author_email='cs@comlounge.net',
      maintainer='Simon Pamies',
      maintainer_email='s.pamies@banality.de',
      url='http://www.webdav.de',
      version='0.9',
      classifiers = [
          'Development Status :: 0.8',
          'Environment :: Console',
          'Environment :: Web Environment',
          'Intended Audience :: End Users',
          'Intended Audience :: Developers',
          'Intended Audience :: System Administrators',
          'License :: GPL',
          'Operating System :: MacOS :: MacOS X',
          'Operating System :: POSIX',
          'Programming Language :: Python',
          ],
      keywords = ['webdav',
                  'server',
                  'dav',
                  'standalone',
                  'library',
                  'gpl',
                  'http',
                  'rfc2518',
                  'rfc 2518'],
      packages=['DAV', ],
      )
